import type { SessionDocument } from '../infrastructure/couchdb/documents/session.document';

export interface RepositoryResult {
  id: string;
  rev: string;
}

/**
 * Data required to create a new session.
 *
 * The session document _id is generated by the service layer.
 */
export interface CreateSessionData {
  type: 'session';

  /**
   * Owner of this session.
   */
  userId: string;

  /**
   * SHA-256 / Argon2 hash of the refresh token.
   *
   * Never store the raw refresh token.
   */
  refreshTokenHash: string;

  /**
   * Optional device identifier.
   *
   * Mobile apps may provide a stable device id.
   */
  deviceId?: string;

  /**
   * Client IP address.
   */
  ip?: string;

  /**
   * Browser / client user agent.
   */
  userAgent?: string;

  /**
   * Current session status.
   */
  status: 'active' | 'revoked' | 'expired';

  /**
   * Session expiration time.
   */
  expiresAt: string;

  /**
   * Last successful activity.
   */
  lastAccessedAt: string;

  createdAt: string;

  updatedAt: string;

  /**
   * Filled only after revocation.
   */
  revokedAt?: string;
}

/**
 * Session repository abstraction.
 *
 * Business logic must never depend on CouchDB.
 */
export abstract class SessionRepository {
  /**
   * Create a new session.
   */
  abstract createSession(sessionId: string, session: CreateSessionData): Promise<RepositoryResult>;

  /**
   * Find a session by its id.
   */
  abstract findById(sessionId: string): Promise<SessionDocument | null>;

  /**
   * Find all sessions belonging to a user.
   */
  abstract findByUserId(userId: string): Promise<SessionDocument[]>;

  /**
   * Find a session using the hashed refresh token.
   *
   * Used during refresh token rotation.
   */
  abstract findByRefreshTokenHash(refreshTokenHash: string): Promise<SessionDocument | null>;

  /**
   * Update an existing session.
   */
  abstract updateSession(session: SessionDocument): Promise<RepositoryResult>;

  /**
   * Revoke a single session.
   */
  abstract revokeSession(sessionId: string): Promise<void>;

  /**
   * Revoke every active session belonging to a user.
   */
  abstract revokeAllUserSessions(userId: string): Promise<void>;

  /**
   * Permanently delete a session.
   */
  abstract deleteSession(sessionId: string): Promise<void>;

  /**
   * Delete all expired sessions.
   *
   * Used by scheduled cleanup jobs.
   */
  abstract deleteExpiredSessions(before: string): Promise<number>;
}
